database-name: 'stas'
connection-string: 'mongodb://localhost:27017'
max-iterations: ''
sample-size: 100
sampleClass: 'SequenceToSequenceSample'
modelName: 'NERModel'
Selector: 'RandomSampleSelector'
master-email: 'admin@gmail.com'
master-password: 'admin@gmail.com'
secret-key: 'example-secretkey'
metrics: 
  - None